### ISSUE TITLE
Numbers don't seem to match

### ISSUE THREAD

**Issue by agandhilogmein** [huggingface/open_asr_leaderboard#18]
1. Which GPU is used for the leaderboard is not clear, Can you please clarify. The readme only has Note: All evaluations are done on single GPU.
2. calc_rtf.py on g4dn.xlarge AWS instance which uses a single T4 gives a RTF of 0.038 for openai/whisper-large-v3 which is very different from what's mentioned on leaderboard i.e about 7.45*10^-3

**Comment by sanchit-gandhi** [comment]
Hey @agandhilogmein - the evaluations use a 40GB A100 GPU. It's clarified on the Space in this commit! https://huggingface.co/spaces/hf-audio/open_asr_leaderboard/commit/02a573ee076008df635f60be3ed91268a512f82c
