### ISSUE TITLE
Nemo ASR evaluation partly broken, numbers don't match

### ISSUE THREAD

**Issue by albertz** [huggingface/open_asr_leaderboard#26]
We wanted to reproduce some WERs from the [OpenASR leaderboard](https://huggingface.co/spaces/hf-audio/open_asr_leaderboard). Specifically for the Nvidia Canary 1B model.

I assume the [`nemo_asr/run_canary.sh`](https://github.com/huggingface/open_asr_leaderboard/blob/main/nemo_asr/run_canary.sh) is the script to run recognition?

We now have some WERs[%] for Earnings22, but they don't match. Specifically:

Hugging face: 12.25
Our with batch size 1: 11.75
Our with batch size 64: 11.89

Any quick idea why that could be?

We noticed also some strange aspects of the code. Here you pass `--pnc=False`:

https://github.com/huggingface/open_asr_leaderboard/blob/5c03c1f85a84ab7a991dcc1b3f14905ec6d632c9/nemo_asr/run_canary.sh#L33

This is probably misleading, as `--pnc=False` will then evaluate `bool("False") == True`, so you end up with `args.pnc == True` in the `run_eval.py` script.

In the `run_eval.py` script, you then check for `pnc is not None`, and if so, you pass `pnc=False` to the `model.transcribe` function:

https://github.com/huggingface/open_asr_leaderboard/blob/5c03c1f85a84ab7a991dcc1b3f14905ec6d632c9/nemo_asr/run_eval.py#L67

But this is strange. In the Nemo `model.transcribe` function, there is no such `pnc` argument:

https://github.com/NVIDIA/NeMo/blob/r1.23.0/nemo/collections/asr/models/aed_multitask_models.py#L349

Once we try to use this script, we thus get the error:
```
TypeError: EncDecMultiTaskModel.transcribe() got an unexpected keyword argument 'pnc'
```

Thus, we modified the code a bit to get the WERs as written above by removing the `pnc` argument. But this indicates that you might have used some different code to get your WER?

Maybe #18 is related?

**Comment by titu1994** [comment]
Canary's inference requires r2.0rc0 or main branch code, 1.23 has other way of providing info via a manifest (also supported in 2.0). About the discrepancy, @nithinraok and I will take a look at it, but pnc is likely the culprit. 

As far as I can ses, it's unrelated to 18

**Comment by Vaibhavs10** [comment]
@titu1994 @nithinraok - any updates on this?

**Comment by albertz** [comment]
Some updates from our side: With r2.0rc0, it works now with `pnc`. That gets us much closer in WERs:

```
testset     | our run | leaderboard number
------------------------------------------
libri       | 2.95    | 2.94
ami         | 13.96   | 14.0
earnings22  | 12.23   | 12.25
gigaspeech  | 10.14   | 10.19
```
We assume the difference just comes from different hardware (we used a 3090 here). Do you think this would explain it?

Note, we also have our own simple beam search implementation which we tried here. When using beam size 1, i.e. greedy, i.e. same as before, but now with our beam search:
```
testset     | our beam search
-----------------------------------
libri       | 2.95
ami         | 13.92
earnings22  | 12.23
```

**Comment by Vaibhavs10** [comment]
Seems good to me! Going to close this issue.
