### ISSUE TITLE
Add Whisper Turbo

### ISSUE THREAD

**Issue by EwoutH** [huggingface/open_asr_leaderboard#40]
Add OpenAI’s new Whisper Turbo model.

- Model: https://huggingface.co/ylacombe/whisper-large-v3-turbo
- Announcement: https://github.com/openai/whisper/discussions/2363
- PR: https://github.com/openai/whisper/pull/2361

**Comment by Vaibhavs10** [comment]
This is now on the leaderboard: https://huggingface.co/spaces/hf-audio/open_asr_leaderboard
